name: Build
on:
    push:
    #workflow_dispatch:
jobs:
    build-common:
        name: Build ${{ matrix.repo-name }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - repo-name: "CME_JsonHelper"
                      java-version: 8
                      branch-name: ""
                    - repo-name: "CME_HealthBarRenderer"
                      java-version: 8
                    - repo-name: "NPE_EventLoader"
                      java-version: 8
                    - repo-name: "CCE_JobBuilder"
                      java-version: 8
                    - repo-name: "NPE_SHEntities"
                      java-version: 8
                    - repo-name: "SIGSEGV_GameNarrator"
                      java-version: 17
                    - repo-name: "CME_EntityTracker"
                      java-version: 8
                    - repo-name: "IIE_Identifier"
                      java-version: 17
                    - repo-name: "CME_LightUpdateMixin"
                      java-version: 8
                    - repo-name: "CME_GoalSelector"
                      java-version: 17
        steps:
            - name: Pull Git Repo （${{ matrix.repo-name }}）
              uses: actions/checkout@v4
              with:
                repository: "ZekerZhayard-s-Random-Patches/${{ matrix.repo-name }}"
                ref: '${{ matrix.branch-name }}'
            - name: Setup JDK ${{ matrix.java-version }}
              uses: actions/setup-java@v4
              with:
                java-version: '${{ matrix.java-version }}'
                cache: 'gradle'
                java-package: 'jdk'
                distribution: 'liberica'
            - name: Build dotJar files
              run: |
                # export GIT_COMMIT_DESC=$(git log --format=%B -n 1 $GITHUB_SHA)
                chmod +x ./gradlew
                ./gradlew clean build --stacktrace
            - name: Publish to Actions Artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.repo-name }}
                path: build/libs

################################################################
    release:
        needs: build-common
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifact Zips
              uses: actions/download-artifact@v4
              with:
                path: build/temp
            - name: "CI Release Prepare"
              id: github-text
              run: |
                echo "build_time=$(TZ=Asia/Shanghai date "+%Y.%m.%d %H:%M")" >> $GITHUB_OUTPUT
                mkdir build/libs
                find build/temp/ -mindepth 1 -maxdepth 1 -type d -exec sh -c 'mv -v "$0"/* build/libs/' {} \;
            - name: Set CI Release Text
              run: | 
                cat > build/ci-build.md << 'EOF'
                Build Time / 构建时间 : ${{ steps.github-text.outputs.build_time }}
                自动同步分支 ${{ github.ref_name }} 的代码，以保持最新
                Synchronize ${{ github.ref_name }} branch code updates, keeping only the latest version
                EOF
            - name: Delete CI Release
              uses: 8Mi-Tech/delete-release-assets-action@main
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                tag: CI-Build
                deleteOnlyFromDrafts: false
            - name: Upload CI Release Tag
              uses: richardsimko/update-tag@v1.0.11
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: CI-Build
            -
              name: Publish to CI Release
              uses: softprops/action-gh-release@v2
              with:
                name: CI Release Build
                tag_name: CI-Build
                prerelease: false
                body_path: build/ci-build.md
                files: build/libs/*
